version: "3"

volumes:
  mongo_data: {}
  mongo_backup: {}
  node_logs: {}

networks:
  app-network:
    driver: bridge

services:
  backend:
    restart: always
    container_name: server_node_test
    build:
      context: .
      dockerfile: compose/node/Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: "mongodb://mongo:27017/server"
    volumes:
      - /home/app/server/node_modules
      - node_logs:/home/app/server/logs
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - app-network
    # tty: true
  mongo:
    restart: always
    container_name: server_mongo_test
    image: mongo:4.2
    command: mongod --storageEngine wiredTiger
    volumes:
      - mongo_data:/data/db
      - mongo_backup:/data/backup
#    ports:
#      - '27017:27017'
    networks:
      - app-network

  redis:
    image: redis:5.0.12-alpine
    container_name: server_redis_local
    networks:
      - app-network

