FROM node:12.16.3-alpine

RUN addgroup -S app && adduser -S app -G app

ENV HOME=/home/app

COPY backend/package*.json $HOME/server/
RUN chown -R app:app $HOME/*

USER app
WORKDIR $HOME/server
RUN npm install

CMD ["npm", "start"]
